export const DEFAULT_SOUNDS = [
  { id: 'default-1', name: 'Air Horn', url: 'https://actions.google.com/sounds/v1/alarms/bugle_tune.ogg', hotkey: '1', isCustom: false, category: 'Alarms', categoryColor: '#ff4b2b' },
  { id: 'default-2', name: 'Boing', url: 'https://actions.google.com/sounds/v1/cartoon/cartoon_boing.ogg', hotkey: '2', isCustom: false, category: 'Cartoon', categoryColor: '#764ba2' },
  { id: 'default-3', name: 'Shatter', url: 'https://actions.google.com/sounds/v1/foley/glass_shatter.ogg', hotkey: '3', isCustom: false, category: 'Foley', categoryColor: '#00d2ff' },
  { id: 'default-4', name: 'Clang', url: 'https://actions.google.com/sounds/v1/cartoon/clang_and_wobble.ogg', hotkey: null, isCustom: false, category: 'Cartoon', categoryColor: '#764ba2' },
  { id: 'default-5', name: 'Faaah', url: 'https://www.myinstants.com/media/sounds/faaah.mp3', hotkey: '5', isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-6', name: 'Dexter meme', url: 'https://www.myinstants.com/media/sounds/dexter-meme.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-7', name: 'BRUH', url: 'https://www.myinstants.com/media/sounds/movie_1.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-8', name: 'gey echo', url: 'https://www.myinstants.com/media/sounds/gey-echo.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-9', name: 'VINE BOOM SOUND', url: 'https://www.myinstants.com/media/sounds/vine-boom.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-10', name: 'rip my granny loud asf', url: 'https://www.myinstants.com/media/sounds/rip-my-granny-loud-asf.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-11', name: 'rizz', url: 'https://www.myinstants.com/media/sounds/rizz-sound-effect.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-12', name: 'Anime Wow', url: 'https://www.myinstants.com/media/sounds/anime-wow-sound-effect.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-13', name: 'anime ahh', url: 'https://www.myinstants.com/media/sounds/anime-ahh.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-14', name: 'Smoke Detector Beep', url: 'https://www.myinstants.com/media/sounds/smoke-detector-beep.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-15', name: 'ACK', url: 'https://www.myinstants.com/media/sounds/ack.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-16', name: 'Error SOUNDSS', url: 'https://www.myinstants.com/media/sounds/error_CDOxCYm.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-17', name: 'spiderman meme song', url: 'https://www.myinstants.com/media/sounds/spiderman-meme-song.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-18', name: 'Tuco: GET OUT', url: 'https://www.myinstants.com/media/sounds/tuco-get-out.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-19', name: 'sad meow song', url: 'https://www.myinstants.com/media/sounds/sad-meow-song.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-20', name: 'Daddyy Chill', url: 'https://www.myinstants.com/media/sounds/daddyy-chill.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-21', name: 'GunShottttt', url: 'https://www.myinstants.com/media/sounds/gunshotjbudden.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-22', name: 'oh my god bro oh hell nah man', url: 'https://www.myinstants.com/media/sounds/oh-my-god-bro-oh-hell-nah-man.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-23', name: 'Prowler', url: 'https://www.myinstants.com/media/sounds/prowler-sound-effect_6bXErot.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-24', name: 'GopGopGop', url: 'https://www.myinstants.com/media/sounds/gopgopgop.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-25', name: 'Huh? Ceeday', url: 'https://www.myinstants.com/media/sounds/ceeday-huh-sound-effect.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-26', name: 'gah dayum', url: 'https://www.myinstants.com/media/sounds/gah-dayum.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-27', name: 'Meme final', url: 'https://www.myinstants.com/media/sounds/meme-de-creditos-finales.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-28', name: 'Another One DJ Khaled', url: 'https://www.myinstants.com/media/sounds/another-one_dPvHt2Z.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-29', name: 'fahhh pump sound', url: 'https://www.myinstants.com/media/sounds/fahhh-pump-sound.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-30', name: 'Core', url: 'https://www.myinstants.com/media/sounds/core-sound-effect.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-31', name: 'Sybau', url: 'https://www.myinstants.com/media/sounds/sybau.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-32', name: 'let me know', url: 'https://www.myinstants.com/media/sounds/let-me-know.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-33', name: 'the weeknd rizzz', url: 'https://www.myinstants.com/media/sounds/the-weeknd-rizzz.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-34', name: 'invincible title car sound', url: 'https://www.myinstants.com/media/sounds/invincible-title-car-sound.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-35', name: 'We do not care (TikTok Sound)', url: 'https://www.myinstants.com/media/sounds/we-do-not-care_phB0mEB.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-36', name: 'Hey let her go!', url: 'https://www.myinstants.com/media/sounds/let-her-go.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-37', name: 'CINEMATIC SUSPENSE RISER', url: 'https://www.myinstants.com/media/sounds/cinematic-suspense-riser.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-38', name: 'gmidao do zap', url: 'https://www.myinstants.com/media/sounds/gmidao-do-zap.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-39', name: 'Careless Whisper', url: 'https://www.myinstants.com/media/sounds/careless_whispers.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-40', name: 'FBI open UP', url: 'https://www.myinstants.com/media/sounds/fbi-open-up-sfx.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-41', name: 'shocking!', url: 'https://www.myinstants.com/media/sounds/shocking_0NL2w3I.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-42', name: 'Buenos dias Papacito', url: 'https://www.myinstants.com/media/sounds/buenos-dias-papacito.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-43', name: 'PAPACITOOOO', url: 'https://www.myinstants.com/media/sounds/papacitoooo.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-44', name: 'Papacito', url: 'https://www.myinstants.com/media/sounds/papacito.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-45', name: 'SEÑORA SU HIJO ESTÁ BIENDO', url: 'https://www.myinstants.com/media/sounds/senora-su-hijo-esta-biendo_dFaNfQi.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-46', name: 'HiJo De MoDoFoquel Niga Bit', url: 'https://www.myinstants.com/media/sounds/hijo-de-p000.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-47', name: 'Hijo put*', url: 'https://www.myinstants.com/media/sounds/hijo-put-xocas.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-48', name: 'CW MI HIJO ES NEGRO', url: 'https://www.myinstants.com/media/sounds/cw_mi-hijo-es-negro.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-49', name: 'HIJO DE TU PINCHE MADRE', url: 'https://www.myinstants.com/media/sounds/hijo_de_tu_pinche_madre.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-50', name: 'ahora si valio vrga hijos de su pta madre', url: 'https://www.myinstants.com/media/sounds/ahora-si-valio-vrga-hijos-de-su-pta-madre.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-51', name: 'Hijo de la Chingada', url: 'https://www.myinstants.com/media/sounds/hijo-de-la-chingada.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-52', name: 'hijo de tu mami', url: 'https://www.myinstants.com/media/sounds/hijo-de-tu-mami.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-53', name: 'instant hijode pta', url: 'https://www.myinstants.com/media/sounds/instant-hijode-pta.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-54', name: 'Callate hijo d pu-', url: 'https://www.myinstants.com/media/sounds/callate-hijo-d-pu.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-55', name: 'Ay papaya de Celaya ay Papantla tus hijos vuelan', url: 'https://www.myinstants.com/media/sounds/ay-papaya-de-celaya-ay-papantla-tus-hijos-vuelan.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-56', name: 'No importa hijo', url: 'https://www.myinstants.com/media/sounds/no-importa-hijo.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-57', name: 'vos sos un boludo', url: 'https://www.myinstants.com/media/sounds/boludo.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-58', name: 'Sos Un Boludo', url: 'https://www.myinstants.com/media/sounds/boludo_2.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-59', name: 'Dale Boludo', url: 'https://www.myinstants.com/media/sounds/dale-boludo.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-60', name: 'Boludo por aqui', url: 'https://www.myinstants.com/media/sounds/boludo_1.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-61', name: 'seba ay boludo', url: 'https://www.myinstants.com/media/sounds/ay_2.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-62', name: 'boludo te la creiste pepe', url: 'https://www.myinstants.com/media/sounds/boludo-te-la-creiste-pepe.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-63', name: 'que queres boludo', url: 'https://www.myinstants.com/media/sounds/que-queres-boludo.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-64', name: 'so boludo vo', url: 'https://www.myinstants.com/media/sounds/so-boludo-vo.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-65', name: 'Pedaso de boludoo', url: 'https://www.myinstants.com/media/sounds/pedaso-de-boludoo.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-66', name: 'No hay plata', url: 'https://www.myinstants.com/media/sounds/no-hay-plata.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-67', name: 'Pipa Pipa Pipa No No No', url: 'https://www.myinstants.com/media/sounds/pipa-pipa-pipa-no-no-no-corto.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-68', name: 'Dale dale dale', url: 'https://www.myinstants.com/media/sounds/dalebydross.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-69', name: 'Anda a laburar!', url: 'https://www.myinstants.com/media/sounds/anda-a-laburar.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-70', name: 'ah la put', url: 'https://www.myinstants.com/media/sounds/ah-la-put.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-71', name: 'creeeo que se equivoco', url: 'https://www.myinstants.com/media/sounds/creeeo-que-se-equivoco.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-72', name: 'Te estan tomando el pelo!', url: 'https://www.myinstants.com/media/sounds/te-estan-tomando-el-pelo.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-73', name: 'NO DIDDY', url: 'https://www.myinstants.com/media/sounds/no-diddy.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-74', name: 'wyatt cadden p diddy', url: 'https://www.myinstants.com/media/sounds/wyatt-cadden-p-diddy.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-75', name: 'diddy no ahhhhhhhhhhhhhhhh', url: 'https://www.myinstants.com/media/sounds/diddy-no-ahhhhhhhhhhhhhhhh.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-76', name: 'ahhhhhhhhh diddy', url: 'https://www.myinstants.com/media/sounds/ahhhhhhhhh-diddy.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-77', name: 'Sicko Mode Meme SFX', url: 'https://www.myinstants.com/media/sounds/the-beginning-of-sicko-mode-sound-effect-for-memes_xAcUeuI.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-78', name: 'Drake embarrassing', url: 'https://www.myinstants.com/media/sounds/drake-embarrassing_Ts9wkE9.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-79', name: 'DRAKE 6', url: 'https://www.myinstants.com/media/sounds/6-god.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-80', name: "W's in de chat", url: 'https://www.myinstants.com/media/sounds/ws-in-de-chat.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-81', name: 'Oh man not again', url: 'https://www.myinstants.com/media/sounds/oh-man-not-again.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-82', name: 'Yeah (Drake)', url: 'https://www.myinstants.com/media/sounds/yeah-drake.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-83', name: 'Provide Drake', url: 'https://www.myinstants.com/media/sounds/provide-drake_iptQ4Mx.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-84', name: 'DRAKE - YA DEAD', url: 'https://www.myinstants.com/media/sounds/drake-ya-dead.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-85', name: 'Drake ahh soundeffect', url: 'https://www.myinstants.com/media/sounds/drake-ahh-soundeffect.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-86', name: 'Drake ESPN.COM RANT', url: 'https://www.myinstants.com/media/sounds/drake-reacts-to-toronto-raptors.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-87', name: 'Mogull', url: 'https://www.myinstants.com/media/sounds/mogull.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-88', name: 'Drake plan', url: 'https://www.myinstants.com/media/sounds/drake-plan.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-89', name: 'Im Sorryyyy (Drake)', url: 'https://www.myinstants.com/media/sounds/im-sorryyyy-drake.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-90', name: 'My Day 1', url: 'https://www.myinstants.com/media/sounds/my-day-1.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-91', name: 'Say that you a lesbian girl me too. Drake', url: 'https://www.myinstants.com/media/sounds/say-that-you-a-lesbian-girl-me-too-drake.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-92', name: 'yoshi ow', url: 'https://www.myinstants.com/media/sounds/yoshi-ow.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-93', name: 'Mission Failed', url: 'https://www.myinstants.com/media/sounds/dank-meme-compilation-volume-17_cutted.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-94', name: 'Millionaire Suspense', url: 'https://www.myinstants.com/media/sounds/5000000-music-mp3cut.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-95', name: 'youre trash kid', url: 'https://www.myinstants.com/media/sounds/ninja-cut.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-96', name: 'PSYCH ! Thats the wrong number', url: 'https://www.myinstants.com/media/sounds/psych_-thats-the-wrong-number.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-97', name: 'donald trump approves this', url: 'https://www.myinstants.com/media/sounds/donald-trump-approves-this.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-98', name: 'They Indicted Me', url: 'https://www.myinstants.com/media/sounds/they-indicted-me_ptD0GKj.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-99', name: 'Access Denied', url: 'https://www.myinstants.com/media/sounds/access-denied_Is238Ly.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-100', name: 'Janet - The Good Place', url: 'https://www.myinstants.com/media/sounds/the-good-place-janet-sound-effect.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-101', name: 'Joe Biden Gibberish', url: 'https://www.myinstants.com/media/sounds/joe-biden-gibberish.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-102', name: 'gdfewfweewgew', url: 'https://www.myinstants.com/media/sounds/gdfewfweewgew.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-103', name: 'My Name is Giovanni Giorgio', url: 'https://www.myinstants.com/media/sounds/my_name_is_giovanni_giorgioconvertitoremp3.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-104', name: 'Zemmour tousse', url: 'https://www.myinstants.com/media/sounds/zemmour-tousse.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-105', name: 'Fetty Wap yeah baby', url: 'https://www.myinstants.com/media/sounds/yeahbaby.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-106', name: 'Michael Rosen: Noice', url: 'https://www.myinstants.com/media/sounds/-click-nice_3.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-107', name: 'Biden Skill Issue', url: 'https://www.myinstants.com/media/sounds/biden-skill-issue.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-108', name: 'Joe Biden - Come On Man', url: 'https://www.myinstants.com/media/sounds/come-on-maaan_h1XE6WF.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' },
  { id: 'default-109', name: 'Goddamnit lil pecker licker', url: 'https://www.myinstants.com/media/sounds/goddamnit-lil-pecker-licker.mp3', hotkey: null, isCustom: false, category: 'Meme', categoryColor: '#fbbf24' }
];
